"use client";

import { BadgeCheck, Building2, Camera, Check, Image as ImageIcon, MessageCircle, Package, Plus, Printer, QrCode, Search, Settings, ShoppingBag, Trash2, Upload, UserRound, Users, WalletCards, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";

type Bill = { id:number; residentName:string; residentAddress:string; feeName:string; period:string; amount:number; status:"lunas"|"belum_lunas"; paidAt:string|null };
type Product = { id:number; name:string; category:string; seller:string; phone:string; price:number; description:string; color:string; available:boolean };
const rupiah=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
const initialProducts:Product[]=[
 {id:1,name:"Nasi Uduk Bu Rina",category:"Kuliner",seller:"Rina Marlina",phone:"6281290112877",price:10000,description:"Nasi uduk hangat, lauk lengkap. Pesan H-1 untuk sarapan dan acara warga.",color:"orange",available:true},
 {id:2,name:"Jasa Pembuatan Website",category:"Jasa",seller:"Budi Santoso",phone:"6281234567801",price:1500000,description:"Website usaha, katalog digital, dan profil UMKM warga dengan harga tetangga.",color:"indigo",available:true},
 {id:3,name:"Kue Basah Aneka Rasa",category:"Kuliner",seller:"Siti Aminah",phone:"6281377218920",price:35000,description:"Paket isi 10, dibuat segar setiap pagi. Cocok untuk rapat dan arisan.",color:"green",available:true},
];

export function MarketplaceView(){
 const [query,setQuery]=useState(""); const [open,setOpen]=useState(false); const [products,setProducts]=useState<Product[]>(initialProducts);
 useEffect(()=>{try{const saved=localStorage.getItem("kasrt-products");if(saved)setProducts(JSON.parse(saved))}catch{}},[]);
 const save=(next:Product[])=>{setProducts(next);try{localStorage.setItem("kasrt-products",JSON.stringify(next))}catch{}};
 const submit=(fd:FormData)=>{const colors=["indigo","orange","green","cyan"];save([{id:Date.now(),name:String(fd.get("name")),category:String(fd.get("category")),seller:String(fd.get("seller")),phone:String(fd.get("phone")).replace(/^0/,"62"),price:Number(fd.get("price")),description:String(fd.get("description")),color:colors[products.length%colors.length],available:true},...products]);setOpen(false)};
 const shown=products.filter(p=>`${p.name} ${p.seller} ${p.category}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="feature-page"><FeatureHeading kicker="EKONOMI LOKAL" title="Marketplace Warga" text="Dukung usaha dan layanan milik tetangga di lingkungan Blok Mawar." action={<button className="btn primary" onClick={()=>setOpen(true)}><Plus size={17}/>Jual Produk</button>}/>
 <div className="market-toolbar"><label><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari produk, jasa, atau penjual..."/></label><span><ShoppingBag size={16}/>{shown.length} produk warga</span></div>
 <div className="product-grid">{shown.map(p=><article className="product-card" key={p.id}><div className={`product-cover ${p.color}`}><span>{p.category}</span><div><Package size={34}/><h3>{p.name}</h3></div><b>{rupiah(p.price)}</b></div><div className="product-body"><span className="stock"><i/>Tersedia</span><p>{p.description}</p><div className="seller"><div className="avatar table-avatar">{p.seller.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><small>PENJUAL WARGA</small><b>{p.seller}</b></div><button onClick={()=>save(products.filter(x=>x.id!==p.id))} title="Hapus produk"><Trash2 size={15}/></button></div><a className="wa-button" target="_blank" href={`https://wa.me/${p.phone}?text=${encodeURIComponent(`Halo ${p.seller}, saya tertarik dengan ${p.name} di Marketplace Blok Mawar.`)}`}><MessageCircle size={17}/>Hubungi Penjual</a></div></article>)}</div>
 {open&&<div className="modal-wrap"><button className="modal-backdrop" onClick={()=>setOpen(false)}/><div className="modal"><div className="modal-head"><div><span>MARKETPLACE WARGA</span><h2>Pasang Produk Baru</h2></div><button className="icon-button" onClick={()=>setOpen(false)}><X/></button></div><form className="modal-form" action={submit}><div className="field"><label>NAMA PRODUK / JASA</label><input name="name" required placeholder="Contoh: Catering harian"/></div><div className="field-row"><div className="field"><label>KATEGORI</label><select name="category"><option>Kuliner</option><option>Jasa</option><option>Fashion</option><option>Kebutuhan Rumah</option><option>Lainnya</option></select></div><div className="field"><label>HARGA</label><input name="price" type="number" required placeholder="0"/></div></div><div className="field-row"><div className="field"><label>NAMA PENJUAL</label><input name="seller" required/></div><div className="field"><label>WHATSAPP</label><input name="phone" required placeholder="0812..."/></div></div><div className="field"><label>DESKRIPSI</label><textarea name="description" required/></div><button className="btn primary submit">Terbitkan Produk</button></form></div></div>}</div>
}

export function ReceiptView({bills,logo}:{bills:Bill[];logo?:string}){
 const [selected,setSelected]=useState(bills[0]?.id??0); const bill=bills.find(b=>b.id===selected); const date=bill?.paidAt?new Date(bill.paidAt):new Date();
 return <div className="feature-page receipt-page"><FeatureHeading kicker="DOKUMEN PEMBAYARAN" title="Kwitansi Digital" text="Bukti pembayaran resmi yang dapat dicetak atau disimpan sebagai PDF." action={<button className="btn dark no-print" onClick={()=>window.print()}><Printer size={17}/>Cetak Kwitansi</button>}/>
 <div className="receipt-selector no-print"><label>Pilih tagihan warga</label><select value={selected} onChange={e=>setSelected(Number(e.target.value))}>{bills.map(b=><option key={b.id} value={b.id}>{b.residentName} — {b.period}</option>)}</select></div>
 <article className="receipt-paper"><div className="receipt-watermark"><Check/></div><header><div className={`receipt-logo ${logo?"has-custom-logo":""}`}>{logo?<img src={logo} alt="Logo RT"/>:<WalletCards/>}<div><h2>KWITANSI RESMI</h2><span>SISTEM KAS DIGITAL RT</span></div></div><div className="receipt-org"><small>NO: KAS/{String(bill?.id??0).padStart(4,"0")}/2026</small><b>RT 002 / RW 014</b><span>Blok Mawar · Perumahan Ciptaland</span></div></header><div className="receipt-lines"><div><label>DITERIMA DARI</label><strong>{bill?.residentName??"—"}</strong></div><div><label>UANG SEJUMLAH</label><strong className="italic">{bill?rupiah(bill.amount):"Nol Rupiah"}</strong></div><div><label>UNTUK PEMBAYARAN</label><strong>{bill?`${bill.feeName} periode ${bill.period}`:"Tidak ada tagihan yang dipilih"}</strong></div></div><footer><div className="receipt-total"><span>TOTAL TERBAYAR</span><b>{rupiah(bill?.amount??0)}</b><em className={bill?.status==="lunas"?"done":"wait"}>{bill?.status==="lunas"?"LUNAS":"BELUM LUNAS"}</em></div><div className="signature"><span>Ciptaland, {date.toLocaleDateString("id-ID",{day:"numeric",month:"long",year:"numeric"})}</span><div className="stamp">KAS RT<br/>002</div><b>AHMAD SURYANA</b><small>BENDAHARA RT</small></div></footer><div className="receipt-note"><BadgeCheck/> Dokumen diterbitkan secara elektronik oleh Sistem KAS RT Blok Mawar.</div></article></div>
}

type AppSettings={name:string;shortName:string;subtitle:string;description:string;account:string;chairman:string;treasurer:string};
export function SettingsView(){
 const defaults={name:"KAS RT BLOK MAWAR",shortName:"KAS RT 002",subtitle:"BLOK MAWAR · CIPTALAND",description:"Sistem pengelolaan kas digital dan layanan warga RT 002 RW 014 Perumahan Ciptaland",account:"Bank BCA 123456789 a/n RT 002 Blok Mawar",chairman:"Bapak Hendra Wijaya",treasurer:"Ahmad Suryana"};
 const [tab,setTab]=useState<"app"|"users">("app"); const [data,setData]=useState<AppSettings>(defaults); const [saved,setSaved]=useState(false); const [logo,setLogo]=useState(""); const [qris,setQris]=useState("");
 useEffect(()=>{try{const x=localStorage.getItem("kasrt-settings");if(x)setData({...defaults,...JSON.parse(x)});setLogo(localStorage.getItem("kasrt-logo")||"");setQris(localStorage.getItem("kasrt-qris")||"")}catch{}},[]);
 const file=(f:File|undefined,setter:(s:string)=>void,key:string)=>{if(!f)return;const r=new FileReader();r.onload=()=>{const v=String(r.result);setter(v);try{localStorage.setItem(key,v)}catch{}};r.readAsDataURL(f)};
 const save=()=>{localStorage.setItem("kasrt-settings",JSON.stringify(data));window.dispatchEvent(new Event("kasrt-settings-updated"));setSaved(true);setTimeout(()=>setSaved(false),2200)};
 return <div className="feature-page"><FeatureHeading kicker="KONFIGURASI" title="Pengaturan" text="Kelola identitas aplikasi, informasi pembayaran, dan pengurus RT."/>
 <div className="settings-tabs"><button className={tab==="app"?"active":""} onClick={()=>setTab("app")}><Settings/>Aplikasi</button><button className={tab==="users"?"active":""} onClick={()=>setTab("users")}><Users/>User Management</button></div>
 {tab==="app"?<div className="settings-card card"><h2>Identitas Aplikasi</h2><div className="field"><label>NAMA APLIKASI</label><input value={data.name} onChange={e=>setData({...data,name:e.target.value})}/></div><div className="field-row"><div className="field"><label>NAMA PENDEK DI SIDEBAR</label><input value={data.shortName} maxLength={22} onChange={e=>setData({...data,shortName:e.target.value})} placeholder="KAS RT 002"/></div><div className="field"><label>SUBJUDUL DI SIDEBAR</label><input value={data.subtitle} maxLength={32} onChange={e=>setData({...data,subtitle:e.target.value})} placeholder="BLOK MAWAR · CIPTALAND"/></div></div><div className="field"><label>KETERANGAN APLIKASI</label><textarea value={data.description} onChange={e=>setData({...data,description:e.target.value})}/></div><div className="upload-grid"><UploadBox title="LOGO APLIKASI" image={logo} onFile={f=>file(f,setLogo,"kasrt-logo")}/><UploadBox title="QRIS PEMBAYARAN" image={qris} onFile={f=>file(f,setQris,"kasrt-qris")}/></div><div className="field"><label>NOMOR REKENING LENGKAP</label><input value={data.account} onChange={e=>setData({...data,account:e.target.value})}/></div><button className="btn primary" onClick={save}>{saved?<><Check/>Tersimpan</>:"Simpan Perubahan"}</button></div>:<div className="user-settings"><div className="card role-card"><div className="role-icon purple"><UserRound/></div><div><span>KETUA RT</span><h3>{data.chairman}</h3><p>Akses laporan dan persetujuan kegiatan.</p></div><button className="dots">•••</button></div><div className="card role-card"><div className="role-icon green"><WalletCards/></div><div><span>BENDAHARA</span><h3>{data.treasurer}</h3><p>Akses penuh transaksi, tagihan, dan kwitansi.</p></div><button className="dots">•••</button></div><div className="card role-card"><div className="role-icon orange"><Users/></div><div><span>WARGA TERDAFTAR</span><h3>12 akun aktif</h3><p>Akses informasi tagihan dan layanan warga.</p></div><button className="dots">•••</button></div></div>}</div>
}

function UploadBox({title,image,onFile}:{title:string;image:string;onFile:(f?:File)=>void}){const ref=useRef<HTMLInputElement>(null);return <div><label className="upload-title">{title}</label><button className="upload-box" onClick={()=>ref.current?.click()}>{image?<img src={image} alt={title}/>:<><span><ImageIcon/></span><b>Klik untuk upload gambar</b><small>PNG atau JPG · Maksimal 2 MB</small></>}<input ref={ref} hidden type="file" accept="image/*" onChange={e=>onFile(e.target.files?.[0])}/></button></div>}
function FeatureHeading({kicker,title,text,action}:{kicker:string;title:string;text:string;action?:React.ReactNode}){return <section className="page-heading feature-heading"><div><p>{kicker}</p><h1>{title}</h1><span>{text}</span></div>{action}</section>}
